---
- name: DevOps Lab Provisioning
  hosts: all
  become: true  

  vars:
    vm_ip: "{{ vm_ip | default('192.168.56.10') }}"

  roles:
    - common    
    - vault     
    - jenkins   
    - zabbix    